substitutions:
  _FOR_RAILS_BUILD_COMMIT: unknown
  _IMAGE: us-central1-docker.pkg.dev/PROJECT/for-rails/for-rails:unknown

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - FOR_RAILS_BUILD_COMMIT=${_FOR_RAILS_BUILD_COMMIT}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
